// Generated by CoffeeScript 1.10.0
(function() {
  var Column;

  Column = (function() {
    function Column(options) {
      this.editable = options.editable, this.editableOnCreate = options.editableOnCreate, this.key = options.key, this.mapValue = options.mapValue, this.text = options.text, this.values = options.values;
      if (this.editable == null) {
        this.editable = true;
      }
      if (this.editableOnCreate == null) {
        this.editableOnCreate = this.editable;
      }
      if (this.mapValue == null) {
        this.mapValue = function(v) {
          return v;
        };
      }
      if (this.text == null) {
        this.text = this.key;
      }
      if (this.key == null) {
        throw 'Column requires key';
      }
      if (typeof this.mapValue !== 'function') {
        throw 'mapValue must be a function';
      }
    }

    Column.prototype.getInitialValue = function() {
      if (this.isSelect()) {
        return this.values[0];
      } else {
        return '';
      }
    };

    Column.prototype.isSelect = function() {
      return this.values != null;
    };

    return Column;

  })();

  module.exports = Column;

}).call(this);
