// Generated by CoffeeScript 1.10.0
(function() {
  var Component, DOM, TBody, THead, Table, createFactory, ref, table,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('react'), DOM = ref.DOM, Component = ref.Component, createFactory = ref.createFactory;

  THead = createFactory(require('./thead'));

  TBody = createFactory(require('./TBody'));

  table = DOM.table;

  Table = (function(superClass) {
    extend(Table, superClass);

    function Table() {
      return Table.__super__.constructor.apply(this, arguments);
    }

    Table.prototype.render = function() {
      return table({}, THead({
        columns: this.props.columns
      }), TBody({
        columns: this.props.columns,
        data: this.props.data,
        onChange: this.props.onChange
      }));
    };

    return Table;

  })(Component);

  module.exports = Table;

}).call(this);
