// Generated by CoffeeScript 1.10.0
(function() {
  var Component, DOM, THead, ref, th, thead, tr,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('react'), DOM = ref.DOM, Component = ref.Component;

  thead = DOM.thead, tr = DOM.tr, th = DOM.th;

  THead = (function(superClass) {
    extend(THead, superClass);

    function THead() {
      return THead.__super__.constructor.apply(this, arguments);
    }

    THead.prototype.render = function() {
      var column;
      return thead({}, tr({}, (function() {
        var i, len, ref1, results;
        ref1 = this.props.columns;
        results = [];
        for (i = 0, len = ref1.length; i < len; i++) {
          column = ref1[i];
          results.push(th({
            key: column.key
          }, column.text));
        }
        return results;
      }).call(this)));
    };

    return THead;

  })(Component);

  module.exports = THead;

}).call(this);
